### PR TITLE
Pubsub

### PR DESCRIPTION
**Pull request by acehreli**
Although incomplete, this seems to work the way Adil described it in truedat's repo.

Adil, before I go any further, what do you think?

Also, as a git confusion, I don't understand why the earlier change to Makefile appears a part of this pull request. :)

### CODE REVIEW

**Comment by adilbaig** [comment]
@acehreli - This looks good.

Re: the makefile. Try updating your fork with this master, and renew the pull request

**Comment by acehreli** [comment]
Back from DConf... :)

Finally, here is some more information:

This change introduces a Subscriber class, which is limited to the operations that a subscribed Redis client can perform: "subscribe", "psubscribe", "ping", etc.

The subscribed messages accumulate at the server until the client

- either calls processMessages(), in which case all messages are pulled to client and corresponding callbacks are executed

- or performs a legal operation like "subscribe"

In the latter case, we queue all existing messages as we search for the response for that final operation. Note that there can be multiple responses as in the case for "unsubscribe" (without a channel name), which means "unsubscribe from all", where each subscribed channel gets a response.

Ali

**Comment by adilbaig** [comment]
Hi @acehreli ,

Just catching up. I'm curious to know why you closed this PR? Do you plan on a new PR after fixing the conflicts?

**Comment by acehreli** [comment]
Yes, I plan to reopen it after I deal with the Makefile issue. I think I 
did what you recommended but the Makefile change was still a part of 
this request. :)

Ali

**Pull request closed without merging**
