### PR TITLE
Fix issue #45: Implement Redis TLS support (except for subscriptions).

### PR DESCRIPTION
**Pull request by FeepingCreature**
See #45 

I didn't add a constructor for subscriptions cause we don't use them and I don't know how non-blocking OpenSSL works.

### CODE REVIEW

**Comment by adilbaig** [comment]
@FeepingCreature - Thanks for the sending this PR! Overall I think this looks good, I don't have much experience in OpenSSL, so i'm relying on your expertise to ensure this is not a new requirement for users across Windows and Linux platforms. If it is I suggest updating the documentation in this PR to match.

Were you also planning to include unittests to test the OpenSSL specific ctor in the follow up CL? I suggest also adding an example in examples/example.d for the same.

LGTM.

**Comment by FeepingCreature** [comment]
Not sure what you mean by "new requirement"? It should only activate if you have openssl active manually.

Also I should probably update this PR first anyways, it's a bit outdated with the state we ended up going with internally temporarily.

**Comment by FeepingCreature** [comment]
Added a separate method for sending authentication. The reason here is that we want to avoid having the password in a GC-managed buffer where it may well live forever. With the method, password goes in, password goes to socket (or OpenSSL), then we can zero the passed buffer out and it'll quickly stop living anywhere.

**Comment by FeepingCreature** [comment]
Hang on! Found an issue.

**Comment by FeepingCreature** [comment]
Instead of keeping the certificates and key around, we can just free them immediately. OpenSSL will keep a reference to them internally.

**Comment by adilbaig** [comment]
The openssl stuff are behind `version{}` blocks so this should be bw compatible just fine. What's missing are docs to connect via OpenSLL and login to Redis.

**Pull request merged**
