### PR TITLE
fix for modern dmd + dub

### PR DESCRIPTION
**Pull request by John-Colvin**
new import rules are much stricter, hench the various import changes I made

dub's `importPaths` and `sourcePaths` are literally what get passed to `-I` so the must be one directory up from the D package root directory. Could use `"importPaths": ["."]` and same for `sourcePaths` but then all the other folders (benchmark, collections, examples) would be exposed

### CODE REVIEW

**Comment by adilbaig** [comment]
@John-Colvin - I've tried this with the latest stable dmd 2.071 and dub 0.9.24. I incorporated your DMD related changes into master manually, but dub is compiling (including benchmarks and examples) just fine. What issues were you facing?

**Comment by John-Colvin** [comment]
It works fine for building tinyredis (the compiler is being run from the root directory of tinyredis), but that's just accidentally correct. When using tinyredis from another package it won't work because the import paths will be wrong.

**Comment by adilbaig** [comment]
@John-Colvin - Alright, confirmed. Rebase your changes on top of my master and resubmit the pull.

Thanks!

**Comment by John-Colvin** [comment]
rebased.

**Pull request merged**
